name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Go environment
      uses: actions/setup-go@v4.0.1

    - name: Initialize Go Module
      run : go mod init my-health

    - name: Golang Tidy
      run : go mod tidy
    - name: Build and Test
      run : |
        go build
        go test ./...
    
    - name: Install golangci-lint
      run : go install github.com/golangci/golangci-lint/cmd/[email protected]


    - name: Lint
      run : golangci-lint run
