name: Build and Test

on:
  push:
    branches:
      - main
      - 'feature/*'
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Go environment
      uses: actions/setup-go@v4.0.1

    - name: Initialize Go Module
      run : go mod init my-health

    - name: Golang Tidy
      run : go mod tidy
  
    - name: Build Apk
      run : go build
      
    - name: Go test
      run : go test ./...
      
  golangci:
    name: lint
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
